
project_id = "sjeaxjdujzdrlkkfdzjc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

# Function for generating personalized technique recommendations
[functions.generate-technique-recommendations]
verify_jwt = true
